# Generated by Django 3.2.9 on 2021-11-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('foodcartapp', '0046_move_address_to_places_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='places.place', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='places.place', verbose_name='Адрес'),
        ),
    ]
