[flake8]
show-source = True
statistics = False
doctests = True

max-complexity = 6
max-line-length = 79

ignore = D100, D101, D102, D103, D104, D105, D106, W503

exclude =
  .git
  __pycache__
  **/migrations/*.py

[isort]
# isort configuration:
# https://github.com/PyCQA/isort/wiki/isort-Settings
include_trailing_comma = true
use_parentheses = true
# Seehttps://github.com/PyCQA/isort#multi-line-output-modes
multi_line_output = 3
line_length = 79

[pytest]
DJANGO_SETTINGS_MODULE = star_burger.settings
python_files = tests.py test_*.py *_tests.py

# Directories that are not visited by pytest collector:
norecursedirs = .git __pycache__

# Extra options:
addopts =
  --strict-markers
  --tb=short
  --doctest-modules

filterwarnings =
  ignore::DeprecationWarning

markers =
  process_article: test core function
